steps:
name: 'gcr.io/cloud-builders/npm'
args: ['install']
steps:\n  - name: 'gcr.io/cloud-builders/npm'\n    args: ['install']\n  - name: 'gcr.io/cloud-builders/npm'\n    args: ['run', 'build']
steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
