name: Deploy to Google Cloud Run
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Build and Deploy to Cloud Run
        run: |
          gcloud run deploy nextjs-app \
            --source=. \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars=DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --service-account=cloudbuild-sa@nextjs-app-462604.iam.gserviceaccount.com
            